In [1]:
try:
    print(1/0)
except ZeroDivisionError:
    print("Cannot divide by zero.")
except Exception as e:
    print("Error occurred:", e)

Cannot divide by zero.


In [2]:
class Pet:
    def __init__(self, name, sound):
        self.name = name
        self.sound = sound

    def speak(self):
        print(self.sound)

my_pet = Pet("Buster", "Woof")
my_pet.speak()

Woof


In [4]:
def decode_string(s):
    stack = []
    
    for char in s:
        if char != ']':
            stack.append(char)
            print(f"Appended '{char}' to stack: {stack}")
        else:
            # Step 1: Get the string inside []
            substr = ''
            while stack and stack[-1] != '[':
                substr = stack.pop() + substr
            stack.pop()  # remove '['
            print(f"Found substring: '{substr}'")
            
            # Step 2: Get the number before [
            num = ''
            while stack and stack[-1].isdigit():
                num = stack.pop() + num
                print(f"Found number: '{num}'")
            
            # Step 3: Repeat and push back to stack
            stack.append(int(num) * substr)
            print(f"Stack after processing: {stack}")
    
    return ''.join(stack)

# Test
input_str = "3[bcd]2[a]"
print(decode_string(input_str))  # Output: aaabcbc


Appended '3' to stack: ['3']
Appended '[' to stack: ['3', '[']
Appended 'b' to stack: ['3', '[', 'b']
Appended 'c' to stack: ['3', '[', 'b', 'c']
Appended 'd' to stack: ['3', '[', 'b', 'c', 'd']
Found substring: 'bcd'
Found number: '3'
Stack after processing: ['bcdbcdbcd']
Appended '2' to stack: ['bcdbcdbcd', '2']
Appended '[' to stack: ['bcdbcdbcd', '2', '[']
Appended 'a' to stack: ['bcdbcdbcd', '2', '[', 'a']
Found substring: 'a'
Found number: '2'
Stack after processing: ['bcdbcdbcd', 'aa']
bcdbcdbcdaa


In [13]:
word='123ab'
word.isdigit()  # Output: False


False

In [2]:
import numpy as np
a = np.array([[1, 2], [3, 4]], dtype=int)
a[1,1]

4

In [7]:
np.sort(a) 
array1 = np.random.randint(0, 10, size=(3, 3))
array2 = np.random.randint(0, 10, size=(3, 3))
print("Array 1:\n", array1)
print("Array 2:\n", array2)

Array 1:
 [[2 4 5]
 [4 5 3]
 [4 1 9]]
Array 2:
 [[8 6 4]
 [3 3 2]
 [2 6 1]]


In [24]:
array2[:2,1:]

array([[6, 4],
       [3, 2]])

In [29]:
arr = np.array([[10, 20, 30], [30, 50, 60], [40, 30, 90]])
a,b,c= np.vstack((arr[0], arr[1], arr[2]))
a

array([10, 20, 30])

In [ ]:
list((set(a)&set(b)&set(c))) # Output: [30, 40, 50]

[30]

: 

In [22]:
b=np.zeros((3, 4))  # Creates a 2x3 array filled with zeros
b.shape
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a='3a'
escaped_a = a.replace('[', '').replace(']', '')
b=print(escaped_a)
for letter in b:
    if letter.isdigit():
        num= int(letter)
        print(f"'{letter}' is a digit.")
    else:
        character = letter
        print(f"'{letter}' is not a digit.")
print(num*character)

In [ ]:
import re
input_str = "3[axe]2[bc]"
num_list = list(map(int, re.findall(r'\d+', input_str)))
#print("Numbers found:", num_list)  # Output: [3, 2]
str_list=re.findall(r'[a-zA-Z]+', input_str)
#print("Strings found:", str_list)  # Output: ['a', 'bc']
final_output = []
for num, s in zip(num_list, str_list):
    final_output.extend([s] * num)
    #print(f"Extended final_output with {s} * {num}: {final_output}")
    result = ''.join(final_output)
print("Final output:", result)  # Output: ['3', '2', 'a', 'b', 'c']


Final output: axeaxeaxebcbc


In [ ]:
prices=[120, 99, 150, 200,30, 50, 80, 90, 110, 140]
discounts=[price*0.9 if price > 100 else price for price in prices ]
discounts

[108.0, 99, 135.0, 180.0, 30, 50, 80, 90, 99.0, 126.0]

In [ ]:
escaped_a = a.replace('[', '\\[').replace(']', '\\]')
print(escaped_a)

In [14]:
fs = frozenset({1, 2})
print(hash(fs))  # ✅ works

# Use as a key in a dict
my_dict = {fs: "immutable set"}
print(my_dict[frozenset({1, 2})]) 

-1826646154956904602
immutable set


In [20]:
set_a = {1, 2, 3}
set_b = {3, 4, 5}
print(set_a & set_b)

{3}


In [24]:
s = {1, 2, 3}
s.add(7)
[x for x in range(10) if x % 2 == 0 if x % 3 != 0]

[2, 4, 8]

In [28]:
d={x:x*x for x in range(1,6)}
d

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

In [19]:
{v: k for k, v in {'a': 1, 'b': 2}.items()}

{1: 'a', 2: 'b'}

In [ ]:
arr = [1, 2, 3, 4, 5,6]
n = len(arr)

for i in range(n // 2):
    print(f"Swapping elements at indices {i} and {n - 1 - i}")
    arr[i], arr[n - 1 - i] = arr[n - 1 - i], arr[i]
    print(f"Swapped {arr[i]} and {arr[n - 1 - i]}: {arr}")

print(arr)  # [5, 4, 3, 2, 1]


Swapping elements at indices 0 and 5
Swapped 6 and 1: [6, 2, 3, 4, 5, 1]
Swapping elements at indices 1 and 4
Swapped 5 and 2: [6, 5, 3, 4, 2, 1]
Swapping elements at indices 2 and 3
Swapped 4 and 3: [6, 5, 4, 3, 2, 1]
[6, 5, 4, 3, 2, 1]


In [9]:
s = "hello"
reversed_s = ""
for char in s:
    print(f"Current character: {char}")
    reversed_s = char + reversed_s
    print(f"Reversed so far: {reversed_s}")
print(reversed_s)  # olleh


Current character: h
Reversed so far: h
Current character: e
Reversed so far: eh
Current character: l
Reversed so far: leh
Current character: l
Reversed so far: lleh
Current character: o
Reversed so far: olleh
olleh


In [15]:
num = 12340
reversed_num = 0

while num > 0:
    print(f"Current number: {num}")
    digit = num % 10  
    print(digit)         # get last digit
    reversed_num = reversed_num * 10 + digit
    print(f"Reversed number so far: {reversed_num}")
    num //= 10                 # remove last digit

print(reversed_num)  # 54321


Current number: 12340
0
Reversed number so far: 0
Current number: 1234
4
Reversed number so far: 4
Current number: 123
3
Reversed number so far: 43
Current number: 12
2
Reversed number so far: 432
Current number: 1
1
Reversed number so far: 4321
4321


In [13]:
123%10

3

In [36]:
import math
a=[3,4,7,5,2,9,8]
first=second =0
for num in a:
    if num>first:     
        second = first
        first=num
        print(f"First: {first}, Second: {second}")
    elif num>second and num != first:
        second = num
        print(f"Second: {second}")


First: 3, Second: 0
First: 4, Second: 3
First: 7, Second: 4
Second: 5
First: 9, Second: 7
Second: 8


In [8]:
array=[3,3,2,3,5,5,6]

result = [array[0]]  # Start with the first element
for i in range(1, len(array)):
    if array[i] != array[i - 1]:  # Check if current element is different from the last added
        result.append(array[i])
print(f" result: {set(result)}")

 result: {2, 3, 5, 6}


In [10]:
def merge_sorted_arrays(arr1, arr2):
    i = j = 0
    result = []
    
    while i < len(arr1) and j < len(arr2):
        if arr1[i] <= arr2[j]:
            result.append(arr1[i])
            print(f"Added {arr1[i]} from arr1")
            i += 1
        else:
            result.append(arr2[j])
            print(f"Added {arr2[j]} from arr2")
            j += 1
    
    # Add remaining elements
    result.extend(arr1[i:])
    result.extend(arr2[j:])
    
    return result

# Example
a = [1, 3, 7]
b = [2, 4, 6]
print(merge_sorted_arrays(a, b))  # [1, 2, 3, 4, 5, 6]


Added 1 from arr1
Added 2 from arr2
Added 3 from arr1
Added 4 from arr2
Added 6 from arr2
[1, 2, 3, 4, 6, 7]
